### ISSUE TITLE
Sassc Ruby should detect presence of existing libsass.so

### ISSUE THREAD

**Issue by edward** [bolandrm/sassc-ruby#8]
@bolandrm how would you feel about having the ext/Rakefile check for an existing `libsass.so` before it compiles its own? This would also involve performing the detection or setting something in `SassC::Native`.

I say this because having just the one built `libsass.so` will speed up CI times for projects that use `sassc-ruby`.

**Comment by bolandrm** [comment]
i'm a bit fuzzy on how this would work.  where does the libsass.so live?  For most CIs, isn't the whole environment cleaned up after each run?

**Comment by edward** [comment]
The libsass.so will live where ever lib files get installed; somewhere like /usr/local/lib depending on your environment setup.

If we can pre-install binaries of libsass.so then we won’t have to compile them every CI run.

**Comment by edward** [comment]
Actually… let’s forget this for now. Gem caching should be sufficient to do what I need.

**Comment by edward** [comment]
@agis I think it’d be neat! I didn’t follow up on this since I had to focus on other stuff urgently but it could still be helpful.

I’d be open to taking a look at a PR with the caveat that I haven’t looked at the code in 3 years and am just coming back to work after being off on parental leave for a year 😬

**Comment by ebgc** [comment]
1+

pls support this - no need to add redundancy - each gem compiling its own lib if lib exists on system already.

i.e. nokogiri supports it via NOKOGIRI_USE_SYSTEM_LIBRARIES variable
